### ISSUE TITLE
Fails to install on Foundry Build 287

### ISSUE THREAD

**Issue by thehaunted318** [websterguy/pf1e-treasure-generator#1]
Trying to install fails on V10 Build 287 

Error: module pf1e-treasure-generator version 0.5 requires a more modern version of the Foundry Virtual Tabletop software: v9 or newer

![image](https://user-images.githubusercontent.com/77417953/194571219-1c2a4cd7-5bba-4f9b-bbdd-4ecce0cafa20.png)

**Comment by evolaric** [comment]
The apparent cause is the version requirement in the module.json file is 'v9' instead of just '9'.

I was able to make the needed changes to a fork, and it seems to work fine.  Will put together a proper pull request once I test it out a bit.
